title: "Sean Murphy"
email: seaniosdevmurphy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my first ever app to find or search for recipes.
baseurl: "/" 
url: "https://hawaiiansurfer4.github.io" 
twitter_username: 
github_username:  # hawaiiansurfer4

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
